### ISSUE TITLE
Initial setup is broken

### ISSUE THREAD

**Issue by scott** [opoloo/lines-engine#22] opened 2018-02-08 17:11 UTC
Looks like a great gem, but the initial setup into a new app does not work.  Instead, upon running the install script, and trying to browse the blog, we get the following error:
```
Showing /Users/scott/Workspace/blog/app/views/lines/articles/index.html.erb where line #2 raised:
Undefined variable: "$max-width".
```
Apparently the variables set in `application.scss` are not available to `article.scss` etc. and that is causing the issue.

#20 has a fix that solved this.

**Comment by thej** [comment] 2018-11-27 13:34
Duplicate of #20

**Closed by thej** 2018-11-27 13:34 UTC
