### ISSUE TITLE
Help Installing

### ISSUE THREAD

**Issue by TuskerIT** [opoloo/lines-engine#26] opened 2018-03-21 10:53 UTC
Hi all installed after some modding and adding [4.2] to all of the migrate tasks.

Now if i go to localhost:3000/blog I get stylesheet errors. It appears variables are missing like $max-width? Where are these set?

**Comment by occorom** [comment] 2018-05-17 19:04
I have the same issues, did you manage to find a solution ?

**Comment by yickting** [comment] 2018-06-05 16:08
https://github.com/opoloo/lines-engine/issues/11

**Comment by thej** [comment] 2018-11-27 13:34
Duplicate of #11

**Closed by thej** 2018-11-27 13:34 UTC
